[package]
name = "yard-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
yard-core = { path = "../yard-core" }
yard-video = { path = "../yard-video" }
yard-audio = { path = "../yard-audio" }

ironrdp.workspace = true
ironrdp-graphics.workspace = true
ironrdp-tls.workspace = true
ironrdp-tokio.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true
rustls.workspace = true
x509-cert.workspace = true
sha2.workspace = true
tracing.workspace = true
thiserror.workspace = true
